// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/10/2026, 2:37:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/xampp/htdocs/gecorwanda/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/plugins/**/*.{js,ts,mjs}","C:/xampp/htdocs/gecorwanda/frontend/composables/**/*.{js,ts,mjs}","C:/xampp/htdocs/gecorwanda/frontend/utils/**/*.{js,ts,mjs}","C:/xampp/htdocs/gecorwanda/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/gecorwanda/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;