// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/17/2026, 9:37:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/GECORWANDA/GECO-TECH-CHANGE/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/plugins/**/*.{js,ts,mjs}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/composables/**/*.{js,ts,mjs}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/utils/**/*.{js,ts,mjs}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/GECORWANDA/GECO-TECH-CHANGE/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;